### ISSUE TITLE
The required permission on the API key should be added to the installation instruction

### ISSUE THREAD

**Issue by whitphx** [combinatrix-ai/ask.sh#19]
I want to restrict the permissions on each API token for the security sake,
so it would be helpful if the minimum required permission is announced in the prompt below asking for the API token during the installation that the users have to allow.

> ** 🌏 Checking OpenAI api_key... **
🤖 OpenAI API key is not set. Please set it now. This will be written to /Users/whitphx/.zshrc. If you do not want me to setup ASK_SH_OPENAI_API_KEY variable, exit now and run the installer again with NO_ASK_OPENAI_API_KEY=1.
You can obtain your API key from https://platform.openai.com/account/api-keys

May be the _write_ permission on _Model capabilities_?

**Comment by hmirin** [comment]
@whitphx Thank you for the feedback. The minimum required permission is _the write permission on Model capabilities_ as you mentioned. I will update the text later.
